mr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^', include('pets.urls', namespace = 'pets')),
]

pets/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
			url(r'^(?P<pk>[0-9]+)/$', views.PetDetailView.as_view(), name='petdetail'),
			url(r'^(?P<pk>[0-9]+)/newevent/$', views.EventAdd.as_view(), name='addevent'),
			url(r'^event/(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='viewevent'),
			url(r'^event/(?P<pk>[0-9]+)/edit$', views.EventUpdate.as_view(), name='changeevent'),
			url(r'^event/(?P<pk>[0-9]+)/delete$', views.EventDelete.as_view(), name='deleteevent'),
			url(r'^(?P<pk>[0-9]+)/edit/$', views.PetUpdate.as_view(), name='changepet'),
			url(r'^(?P<pk>[0-9]+)/petevents/$', views.PetEventsView.as_view(), name='petevents'),
			url(r'^$', views.calendar, name='calendar'),
			url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.calendar, name='calendar'),
			url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.CalendarDay.as_view(), name='day'),
			url(r'^newpet/$', views.PetAdd.as_view(), name='newpet'),
			url(r'^petlist/$',views.PetsList.as_view(), name='petlist'),
			url(r'^newspecies/$',views.AddSpecies.as_view(),  name='newspecies')
			]

pets/models.py
#coding: utf8

import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User


class Species(models.Model):
	genus = models.CharField('Род',max_length=20)
	species = models.CharField('Вид',max_length=20)
	suspecies = models.CharField('Подвид',max_length=20, blank=True)

	def __str__(self):
		sp_name = (self.genus, self.species, self.suspecies)
		return ' '.join(sp_name)

	class Meta(object):
		ordering = ['genus', 'species', 'suspecies']
		verbose_name = 'Вид'
		verbose_name_plural = 'Виды'
		unique_together = (('genus', 'species', 'suspecies'),)

class Pets(models.Model):
	Gen = (
		('0', 'Неизвестно'),
		('1', 'Самец'),
		('2', 'Самка'))
	u_name = models.ForeignKey(User)
	pet_name = models.CharField('Имя питомца', max_length=50)
	species = models.ForeignKey(Species, on_delete=models.DO_NOTHING, 
		 verbose_name = 'Вид животного', related_name = 'keepers')
	morph = models.CharField('Морфа',max_length=50, blank = True)
	gender = models.CharField('Пол',max_length=1, choices = Gen)
	birth_date = models.IntegerField('Дата рождения',blank = True, null = True)
	birth_month = models.IntegerField('Месяц рождения',blank = True, null = True)
	birth_year = models.IntegerField('Год рождения',blank = True, null = True)
	fed_freq = models.IntegerField('Частота кормления', blank = True, null = True)
	pet_comment = models.TextField('Комментарий',blank = True)
	is_dead = models.BooleanField(default = False) #, editable = False)

	def __str__(self):
		return self.pet_name

	def get_absolute_url(self):
		return  '/%i' % self.id

	def form_birth_date(self):
		date_ar = []
		for i in (self.birth_date, self.birth_month, self.birth_year):
			if i:
				date_ar.append(i)
			else:
				date_ar.append(0)
		#return '.'.join(date_ar)
		return '{:02}.{:02}.{:04}'.format(*date_ar)

	def temp_birth_date(self):
		RU_MONTH_VALUES = {
    1:'январь',
    2:'февраль',
    3:'март',
    4:'апрель',
    5:'май',
    6:'июнь',
    7:'июль',
    8:'август',
    9:'сентябрь',
    10:'октябрь',
    11:'ноябрь',
    12:'декабрь'}

		date_ar = []
		if self.birth_date and self.birth_month and self.birth_year:
			return datetime.date(self.birth_year, self.birth_month, self.birth_date)
		elif self.birth_month and self.birth_year:
			return '%s %d г.' % (RU_MONTH_VALUES[datetime.date(self.birth_year, self.birth_month, 1).month], datetime.date(self.birth_year, self.birth_month, 1).year)
		elif self.birth_year:
			return '%d г.' % datetime.date(self.birth_year, 1, 1).year
		else:
			return None



	'''
	def calculate_age:
		if not species.birth_year: return 'Неизвестно'
		day = int(self.birth_date) if self.birth_date else 15
		month = int(self.birth_month) if self.birth_month else 6
		year = int(self.birth_year)
		birthday = datetime.date(year, month, day)
		today = datetime.date.today()
		return (today-birthday).days'''


	class Meta(object):
		ordering = ['pet_name']
		verbose_name = 'Питомец'
		verbose_name_plural = 'Питомцы'
		unique_together = (('u_name', 'pet_name'),)


class Events(models.Model):
	eventtype = (
		('F', 'Кормление'),
		('FF', 'Принудительное кормление'),
		('RF', 'Отказ от корма'),
		('R', 'Срыг'),
		('S', 'Линька'),
		('SB', 'Проблемная линька'),
		('HP', 'Проблемы со здоровьем'),
		('HC', 'Ветеринарные процедуры'),
		('B', 'Зимовка'),
		('C', 'Спаривание'),
		('L', 'Откладка яиц/роды'),
		('D', 'Смерть'),
		('O', 'Другое'))
	pet = models.ForeignKey(Pets)
	event_type = models.CharField('Событие', max_length=2, choices = eventtype, default = 'F')
	event_date = models.DateField('Дата')
	event_comment = models.TextField('Комментарий', blank = True)
	reminde_me = models.DateField('Напомнить мне', blank = True, null = True)
	reminder_comment = models.TextField('Текст напоминания', blank = True)

	def get_absolute_url(self):
		return '/event/%i' % self.id  

	class Meta(object):
		ordering = ['event_date']
		verbose_name = 'Event'
		verbose_name_plural = 'Events'

pets/forms.py
# coding: utf8

from django import forms
from django.core.exceptions import ValidationError
from .models import Pets, Events, Species
import re, datetime

class PetForm(forms.ModelForm):
	form_birth_date = forms.CharField (label = 'Дата рождения', max_length = 11, 
		required = False, help_text = '''В формате ГГГГ, ММ.ГГГГ или ДД.ММ.ГГГГ''')
	pet_name = forms.CharField(label = 'Имя питомца', required = False, help_text = '''Можно оставить поле пустым.
	 Имя будет сгенерировано из видового названия.''')
	class Meta(object):
		model = Pets
		fields = ('pet_name', 'species', 'morph', 'gender', 
			'form_birth_date', 'fed_freq', 'pet_comment')
		help_texts = {'fed_freq': 'Рекомендуемая частота кормлений. Будет использоваться для напоминаний о кормлении',
		'pet_comment': "Дополнительная информация, не включенная в другие поля"
		}

	def clean_form_birth_date(self):
		inp_data = self.cleaned_data['form_birth_date']
		error = ValidationError("Проверьте правильность ввода даты!")
		if not re.match('^(([0-9]{2}\.){,2}[0-9]{4})?$', inp_data):
			raise error
		if inp_data:
			data=inp_data.split('.')
			now = datetime.date.today()
			y = int(data.pop())
			if y<1950: raise error
			try:
				mm = int(data.pop())
				m = mm if mm!=0 else now.month
			except IndexError:
				m = now.month
			try:
				dd = int(data.pop())
				d = dd if dd!=0 else now.day
			except IndexError:
				d = now.day
			try:
				bd = datetime.date(y,m,d)
			except ValueError:
				raise error
			if bd > now:
				raise error
		return inp_data

class AddSpeciesForm(forms.ModelForm):
	class Meta(object):
		model = Species
		fields = '__all__'


class EventForm(forms.ModelForm):

	class Meta(object):
		model = Events
		exclude = ('pet',)
		help_texts = {'event_comment': 'Любые комментарии: тип и количество КО, поведение при кормлении и т.д.', 
		'reminde_me': 'Заполните это поле, если животное требует дополнительно обратить на себя внимание через\
		 некоторое время. Формат даты DD.MM.YYY', 'reminder_comment': 'Текст напоминания'}

pets/views.py
from django.shortcuts import render, redirect, render_to_response
from django.utils.safestring import mark_safe
from django.views import generic
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.template import RequestContext
from django.http import HttpResponse

from calendar import HTMLCalendar
from itertools import groupby
import datetime

from django.utils.html import conditional_escape as esc

from pets.forms import PetForm, EventForm, AddSpeciesForm
from .models import Events, Pets

class GetObjectMixin():
	def get_object(self):
		object = super().get_object()
		if self.request.user == object.u_name:
			return object
		else:
			raise PermissionDenied

class PetFormMixin():
	'''Form validation at pet creation/update'''
	def form_valid(self, form):
		birth_date_ff = form.cleaned_data['form_birth_date']
		if birth_date_ff:
			birth_date_ff = birth_date_ff.split('.')[::-1]
		else:
			birth_date_ff = []
		pet_name_ff = form.cleaned_data['pet_name']
		instance = form.save(commit=False)
		instance.u_name = self.request.user
		data = []
		for k in range(3):
			try:
				data.append(birth_date_ff.pop(0))
			except IndexError:
				data.append(None)
		instance.birth_year, instance.birth_month, instance.birth_date = data
		if not pet_name_ff:
			psn = instance.species.__str__()
			uniq, i = False, 0
			while uniq == False:
				i+=1
				pr_pet_name = '%s %s' % (psn, i)
				if not Pets.objects.filter(u_name=self.request.user, pet_name=pr_pet_name).exists():
					instance.pet_name = pr_pet_name
					uniq = True
		instance.save()
		self.object = instance
		return redirect(self.get_success_url())

class PetsList(generic.ListView):
	model = Pets
	template_name = 'pets/petlist.html'
	context_object_name = 'pets'

	def get_queryset(self):
		pets = Pets.objects.filter(u_name=self.request.user)
		return pets

class PetDetailView(GetObjectMixin, generic.DetailView):
	model = Pets
	context_object_name = 'pet'
	template_name = 'pets/pet.html'

class PetAdd(PetFormMixin, generic.edit.CreateView):
	form_class = PetForm
	template_name = 'pets/pets_form.html'

class PetUpdate(PetFormMixin, GetObjectMixin, generic.edit.UpdateView):
	form_class = PetForm
	template_name = 'pets/pets_form.html'
	model = Pets

	def get_initial(self):
		initial = super(PetUpdate, self).get_initial()
		initial['form_birth_date'] = self.object.form_birth_date
		return initial

class EventAdd(GetObjectMixin, generic.edit.CreateView):
	form_class = EventForm
	model = Events
	template_name = 'pets/event_form.html'

	def get_initial(self):
		initial = super(EventAdd, self).get_initial()
		initial['event_date'] = datetime.date.today()
		return initial

	def get_context_data(self, **kwargs):
		context = super(EventAdd, self).get_context_data(**kwargs)
		pet = Pets.objects.get(id = self.kwargs['pk'])
		context['pet_name'] = pet
		return context

	def form_valid(self, form):
		instance = form.save(commit = False)
		instance.pet = Pets.objects.get(id = self.kwargs['pk'])
		instance.save()
		self.object = instance
		if self.object.event_type == 'D':
			pet = self.object.pet
			pet.is_dead = True
			pet.save()
		return redirect(self.get_success_url())

class  EventDetail(generic.DetailView):
	model = Events
	context_object_name = 'event'
	template_name = 'pets/event.html'

	def get_object(self):
		object = super().get_object()
		if self.request.user == object.pet.u_name:
			return object
		else:
			raise PermissionDenied

class EventUpdate(GetObjectMixin, generic.edit.UpdateView):
	form_class = EventForm
	model = Events
	template_name = 'pets/event_form.html'

	def form_valid(self, form):
		instance = form.save()
		self.object = instance
		return redirect(self.get_success_url())

class EventDelete(GetObjectMixin,generic.edit.DeleteView):	
	model = Events
	template_name = 'pets/delete_event.html'

	def get_success_url(self):
		eventid = self.kwargs['pk']
		pet = Events.objects.get(pk = eventid).pet
		return '%s/petevents' % pet.get_absolute_url()

class EventsCalendar(HTMLCalendar):
    '''
    link: http://uggedal.com/journal/creating-a-flexible-monthly-calendar-in-django/
    '''
    def __init__(self, events):
        super(EventsCalendar, self).__init__()
        self.events = self.group_by_day(events)

    def formatday(self, day, weekday):

        green = '<img src="/static/images/g.png" />'
        yellow = '<img src="/static/images/y.png" />'
        orange = '<img src="/static/images/o.png" />'
        red = '<img src="/static/images/r.png" />'
        sred = '<img src="/static/images/sr.png" />'
        pink  = '<img src="/static/images/p.png" />' 
        viol = '<img src="/static/images/v.png" />'
        black = '<img src="/static/images/bl.png" />'
        grey = '<img src="/static/images/gr.png" />'
            	
        if day != 0:
        	cssclass = self.cssclasses[weekday]
        	if datetime.date.today() == datetime.date(self.year, self.month, day):
        		cssclass += ' today'
        	if day in self.events:
        		ev_types = set()
        		cssclass += ' filled'
        		for event in self.events[day]:
        			if event.event_type == 'F':
        				ev_types.add(green)
        			elif event.event_type == 'S':
        				ev_types.add(yellow)
        			elif event.event_type == 'FF' or event.event_type == 'RF' or event.event_type == 'SB':
        				ev_types.add(orange)
        			elif event.event_type == 'R' or event.event_type == 'HP':
        				ev_types.add(red)
        			elif event.event_type == 'HC':
        				ev_types.add(sred)
        			elif event.event_type == 'B':
        				ev_types.add(pink)
        			elif event.event_type == 'C' or event.event_type == 'L':
        				ev_types.add(viol)
        			elif event.event_type == 'D':
        				ev_types.add(black)	
        			else:
        				ev_types.add(grey)
        		return self.day_cell(cssclass, '<a href = "/%d/%02.d/%02.d">%d  %s</a>'% (self.year, self.month, day, day, ''.join(ev_types)))
        	return self.day_cell(cssclass, day)
        return self.day_cell('noday', '&nbsp;')

    def formatmonth(self, year, month):
        self.year, self.month = year, month
        return super(EventsCalendar, self).formatmonth(year, month)

    def group_by_day(self, events):
        field = lambda event: event.event_date.day
        return dict(
            [(day, list(items)) for day, items in groupby(events, field)]
        )

    def day_cell(self, cssclass, body):
        return '<td class="%s">%s</td>' % (cssclass, body)

def calendar(request, year=datetime.date.today().year, month=datetime.date.today().month):
  month = int(month)
  year = int(year)
  def find_last_next_month(year, month):
  	'''Find previous and next month'''
  	cur_date = datetime.date(year, month, 15)
  	step = datetime.timedelta(days=30)
  	next, prev = cur_date + step, cur_date - step
  	nmonth, nyear = '{:02}'.format(next.month), next.year
  	pmonth, pyear = '{:02}'.format(prev.month), prev.year
  	res = {'nmonth': nmonth, 'nyear': nyear, 'pmonth': pmonth, 'pyear': pyear}
  	return res 
  my_events = Events.objects.order_by('event_date').filter(
    event_date__year=year, event_date__month=month, pet__u_name=request.user
  )
  cal = EventsCalendar(my_events).formatmonth(year, month)
  flnm = find_last_next_month(year, month)
  flnm.update({'calendar': mark_safe(cal),'month': '{:02}'.format(month), 'year': year, 'user': request.user})
  return render_to_response('pets/cal_template.html', flnm)

class PetEventsView(GetObjectMixin, generic.ListView):
	model = Events
	template_name = 'pets/petevents.html'
	context_object_name = 'events'

	def get_context_data(self, **kwargs):
		context = super(PetEventsView, self).get_context_data(**kwargs)
		context['petid'] = self.kwargs['pk']
		context['petname'] = Pets.objects.get(id=self.kwargs['pk'])
		return context

	def get_queryset(self):
		list_of_events = Events.objects.filter(pet=self.kwargs['pk'])
		return list_of_events

class CalendarDay(generic.ListView):
	model = Events
	template_name = 'pets/calendarday.html'
	context_object_name = 'events'

	def get_queryset(self):
		day, month, year = map(int, (self.kwargs['day'], self.kwargs['month'], self.kwargs['year']))
		data = datetime.date(year, month, day)
		events = Events.objects.filter(pet__u_name = self.request.user, event_date = data)
		return events

class AddSpecies(generic.edit.CreateView):
	form_class = AddSpeciesForm
	template_name = 'pets/addspecies.html'
	success_url = '/newpet'

	def form_valid(self, form):
		instance = form.save()
		return redirect(self.success_url)

pets/templates/pets/addspecies.html
{% extends 'pets/main.html' %}

{% block information %}
<form action="" method="post">
	<table class  = 'form'>
    {% csrf_token %}
    {{ form.as_table }}
    </table>
    <button type='Submit' class="success hollow button">Создать</button>
</form>
<div clss="clear"></div>
{% endblock %}

pets/templates/pets/cal_template.html
{% extends 'pets/main.html' %} 
{% load static %}
{% block information %}
<hr>
<div id="calendar">
    {{ calendar }}
</div>
<div id="legend">
Обозначения:<p>
<img src="{% static 'images/g.png' %}" /> - кормление<br>
<img src="{% static 'images/y.png' %}" /> - линька<br>
<img src="{% static 'images/o.png' %}" /> - отказ от корма, принудительное кормление, проблемная линька<br>
<img src="{% static 'images/r.png' %}" /> - срыг, проблемы со здоровьем<br>
<img src="{% static 'images/sr.png' %}" /> - ветеринарные процедуры<br>
<img src="{% static 'images/p.png' %}" /> - зимовка<br>
<img src="{% static 'images/v.png' %}" /> - спаривание, роды, откладка яиц<br>
<img src="{% static 'images/bl.png' %}" /> - смерть<br>
<img src="{% static 'images/gr.png' %}" /> - другое<br>
</div><p>
<div class="clear"></div>
<a href = '{% url 'pets:calendar' pyear pmonth %}'><<Раньше<<</a>
<a href = '{% url 'pets:calendar' %}'>  Текущий месяц  </a>
<a href = '{% url 'pets:calendar' nyear nmonth %}'>>>Позже>></a>
<hr>
<div class="clear"></div>
{% endblock %}

pets/templates/pets/calendarday.html
{% extends 'pets/main.html' %} 

{% block information %}
<hr>
<div class="row">
  <div class="small-9 columns small-centered">
{% for event in events %}
<article class="event">
        <div class="event-date">
          <p class="event-month">{{ event.event_date|date:"d" }}</p>
          <p class="event-day">{{ event.event_date|date:"b" }}</p>
        </div>

        <div class="event-desc">
          <h4 class="event-desc-header">{{event.pet}}</h4>
          <p class="event-desc-detail"><span class="event-desc-time"></span>{{ event.get_event_type_display }}</p>
          <a href="{% url 'pets:viewevent' event.id %}" class = 'success hollow button'>Просмотреть событие</a>
          <a href="{% url 'pets:deleteevent' event.id %}" class="secondary hollow button">Удалить событие</a>
        </div>
      </article>
      <hr>

<!--tr>
<td><a href="{% url 'pets:viewevent' event.id %}">{{event.pet}} {{ event.get_event_type_display }}</a></td>
<td><div class = 'smallbutton'><a href="{% url 'pets:deleteevent' event.id %}">Удалить событие.</a></td>
</tr-->
{% endfor %}
</div></div>
<hr>
{% endblock %}
<div clss="clear"></div>

pets/templates/pets/delete_event.html
{% extends 'pets/main.html' %} 

{% block information %}
<form action="" method="post">
Вы действительно хотите удалить это событие?
    {% csrf_token %}
    <button class="success hollow button">Удалить</button>
</form>
{% endblock %}

pets/templates/pets/event.html
{% extends 'pets/main.html' %} 

{% block information %}
<hr>
<h4>Питомец: {{ event.pet }}</h1><p>
Событие: {{ event.get_event_type_display }}<p>
Дата: {{ event.event_date }}<p>
Комментарий: {{ event.event_comment|default:'не добавлен.' }}<p>
Напомнить: {{ event.reminde_me|default:'не указано.' }}<p>
Комментарий к напоминанию: {{ event.reminder_comment|default:'не добавлен.' }}<p>
<hr>
<div class="clear"></div>
<a href="{% url 'pets:changeevent' event.id %}" class="success button">Редактировать</a>
<a href="{% url 'pets:petdetail' event.pet.id %}" class="success button">Назад к питомцу</a>
<a href="{% url 'pets:petevents' event.pet.id %}" class="success button">Назад к списку событий</a>

{% endblock %}

pets/templates/pets/event_form.html
{% extends 'pets/main.html' %}

{% block information %}
<h4>Создание/pедактирование события для питомца: {{ pet_name }}{{ object.pet }}</h4>
<form action="" method="post">
	<table class = 'form'>
    {% csrf_token %}
    {{ form.as_table }}
    </table>
    <button type='Submit' class="success hollow button">Создать</button>
</form>
<div clss="clear"></div>
{% if object %}
<a href="{% url 'pets:petdetail' object.pet.id %}" class="success button">Вернуться к питомцу {{ object.pet }}</a>
{% endif %}
{% if pet_name %}
<a href="{% url 'pets:petdetail' pet_name.id %}" class="success button">Вернуться к питомцу {{ pet_name }}</a>
{% endif %}
{% endblock %}

pets/templates/pets/main.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' type='text/css' href = '{% static 'pets/styles.css' %}'>
    <link rel="stylesheet" href='{% static 'pets/css/foundation.css' %}'>
    <title>MyPet - календарь террариумиста</title>
    <link rel="shortcut icon" type="image/png" href='{% static "images/favicon.ico" %}'/>
 </head>
<body>
<h6>Добро пожаловать!</h1>
<a href="{% url 'pets:calendar' %}" class="button">Мой календарь</a><br/>
{% block login %}{% endblock %}
{% block information %}{% endblock %}
<a href="{% url 'pets:petlist' %}" class="success button">К списку питомцев</a>
</body>
</html>

pets/templates/pets/pet.html
{% extends 'pets/main.html' %} 

{% block information %}
<hr>
<h4>Вы смотрите карточку питомца: {{ pet.pet_name }}</h1><p>
<b>Пол:</b> {{ pet.get_gender_display }}<p>
<b>Вид:</b> {{ pet.species }}<p>
<b>Морфа:</b> {{ pet.morph|default:"не указана" }}<p>
<b>Дата рождения:</b> {{ pet.temp_birth_date|default:"неизвестна" }}<p>
<b>Рекомендуемая частота кормления:</b> {% if pet.fed_freq %}
раз в {{ pet.fed_freq }} дней
{% else %}
не указана
{% endif %}
<p>
{{ pet.pet_comment }}<p>
<hr>
<div style="clear:both; height: 50px;"></div>
<a href="{% url 'pets:changepet' pet.id %}" class="success button">Редактировать</a>
{% if pet.is_dead = False %}
<a href="{% url 'pets:addevent' pet.id %}" class="success button">Добавить событие</a>
{% else %}
<div class="secondary button">Добавить событие</div>
{% endif %}
<a href="{% url 'pets:petevents' pet.id %}" class="success button">Посмотреть прошлые события</a>
{% endblock %}

pets/templates/pets/petevents.html
{% extends 'pets/main.html' %} 

{% block information %}
<h4>Вы смотрите историю событий для питомца: {{ petname }}</h1>
<hr>
<div class="row">
  <div class="small-9 columns small-centered">
{% if not events %}
Вы не добавили ни одного события для этого питомца.
{% endif %}
{% for event in events %}
    <article class="event">

        <div class="event-date">
          <p class="event-month">{{ event.event_date|date:"d" }}</p>
          <p class="event-day">{{ event.event_date|date:"b" }}</p>
        </div>

        <div class="event-desc">
          <h4 class="event-desc-header">{{ event.get_event_type_display }}</h4>
          <p class="event-desc-detail"><span class="event-desc-time"></span>{{ event.event_comment }}</p>
          <a href="{% url 'pets:viewevent' event.id %}" class = 'success hollow button'>Просмотреть событие</a>
          <a href="{% url 'pets:deleteevent' event.id %}" class="secondary hollow button">Удалить событие</a>
        </div>
      </article>
      <hr>
{% endfor %}
</div></div>
<hr>
<div style="clear:both; height: 50px;"></div>
{% if pet.is_dead = False %}
<a href="{% url 'pets:addevent' pet.id %}" class="success button">Добавить событие</a>
{% else %}
<div class="secondary button">Добавить событие</div>
{% endif %}
<a href="{% url 'pets:petdetail' petid %}" class="success button">Назад к питомцу</a>
{% endblock %}

pets/templates/pets/petlist.html
{% extends 'pets/main.html' %} 

{% block information %}
<hr>
{% if not pets %}
Вы не добавили ни одного питомца.
{% endif %}
<ul>
{% for pet in pets %}
<li>
<a href="{% url 'pets:petdetail' pet.id %}">{{pet.pet_name}}</a>
</li>
{% endfor %}
</ul>
<hr>
<div class="clear"></div>
<a href="{% url 'pets:newpet' %}" class="success button">Добавить питомца</a>
{% endblock %}

pets/templates/pets/pets_form.html
{% extends 'pets/main.html' %}

{% block information %}
<h4>Создание/редактирование питомца {{ object.pet_name }}</h4>
<p><a href="{% url 'pets:newspecies' %}"class="success hollow button">Новый вид</a><span class="helptext"> Добавить вид, которого нет в выпадающем списке. Введенные ранее в форму данные будут утеряны!</span>
<p>
<form action="" method="post">
	<table class = 'form'>
    {% csrf_token %}
    {{ form.as_table }}
    </table>
    <button type='Submit' class="success hollow button">Создать</button>
    </form>
 <div class="clear"></div>
{% if object %}
<a href="{% url 'pets:petdetail' object.id %}" class="success button">Вернуться к питомцу {{ object.pet_name }}</a>
{% endif %}
{% endblock %}